package com.happiestMinds.mappingDummy;
// Generated Sep 20, 2017 11:51:49 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "UserManagement", uniqueConstraints = { @UniqueConstraint(columnNames = "mobileNumber"),
		@UniqueConstraint(columnNames = "emailId") })
public class User implements java.io.Serializable {

	private long id;
	private Address address;
	private String name;
	private String password;
	private String dob;
	private String mobileNumber;
	private String emailId;
	private Byte status;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(long id, Address address, String name, String password, String dob, String mobileNumber, String emailId,
			Byte status) {
		this.id = id;
		this.address = address;
		this.name = name;
		this.password = password;
		this.dob = dob;
		this.mobileNumber = mobileNumber;
		this.emailId = emailId;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addressId")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "dob", length = 45)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "mobileNumber", unique = true, length = 13)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "emailId", unique = true, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
